FROM openjdk:8u212-jdk-slim

# Maintainer Info
LABEL maintainer="yogendra.yadav@nagarro.com"

VOLUME /tmp

# The application's jar file (when packaged)
ARG JAR_FILE=target/aggregatorservice-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} aggregatorservice.jar

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/aggregatorservice.jar"]

EXPOSE 8083